sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dockerhound/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dockerhound/react-test npm test -- --coverage

after_success:
  - docker build -t dockerhound/multi-client ./client
  - docker build -t dockerhound/multi-nginx ./nginx
  - docker build -t dockerhound/multi-server ./server
  - docker build -t dockerhound/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dockerhound/multi-client
  - docker push dockerhound/multi-nginx
  - docker push dockerhound/multi-server
  - docker push dockerhound/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-921021935259'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
