sudo: required
services:
  - docker

before_install:
  - docker build -t nishanth/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run nishanth/react-test npm test -- --coverage

after_success:
  - docker build -t nishanth/multi-client -f ./client
  - docker build -t nishanth/multi-nginx -f ./nginx
  - docker build -t nishanth/multi-server -f ./server
  - docker build -t nishanth/multi-worker -f ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  - docker push nishanth/multi-client
  - docker push nishanth/multi-nginx
  - docker push nishanth/multi-server
  - docker push nishanth/multi-worker
